### ISSUE TITLE
pubspe.yaml error

### ISSUE THREAD

**Issue by dishaaach03** [AmitXShukla/Healthcare-Management-App-Flutter_Firebase#3]
sir can you please mention the root of the project 
also i'm not able to sort pubspec.yaml

thankyou sir

**Comment by AmitXShukla** [comment]
pubspec.yaml file is located inside src folder. 

https://github.com/AmitXShukla/Healthcare-Management-App-Flutter_Firebase/tree/master/src

CD into src folder, then run flutter run
