### ISSUE TITLE
Dependency issue while running 

### ISSUE THREAD

**Issue by Mathewsaji1** [AmitXShukla/Healthcare-Management-App-Flutter_Firebase#4]
![IMG_0381](https://github.com/AmitXShukla/Healthcare-Management-App-Flutter_Firebase/assets/137825722/e108e59b-82dd-4544-8355-a16960f9ca2a)

please refer the above link. As we also nee to this flutter environment. Couldn’t understand the issue properly.

**Comment by AmitXShukla** [comment]
I believe, error is very clear, your current Flutter version (latest) has Null safety on by default.
You are running an old version project on new Flutter SDK. So you have two options, 
1. either run this project as 
flutter run --no-sound-null-safety
2. or, upgrade pspec.yaml file, as suggested
change line #9 to sdk: >=2.12.0 < 3.0.5
