### ISSUE TITLE
The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0'

### ISSUE THREAD

**Issue by Sunil1999kpm** [AmitXShukla/Healthcare-Management-App-Flutter_Firebase#5]
I cloned this rep using git but when I tried pub get  it threw a error,please help me with this
![error](https://github.com/AmitXShukla/Healthcare-Management-App-Flutter_Firebase/assets/53272821/ee45ac18-d7ff-471c-802b-b5dccea64eeb)
Resolving dependencies...
The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0'
or higher to enable null safety.

The current Dart SDK (3.0.5) only supports null safety.

For details, see https://dart.dev/null-safety

**Comment by AmitXShukla** [comment]
I believe, error is very clear, your current Flutter version (latest) has Null safety on by default.
You are running an old version project on new Flutter SDK. So you have two options,

    either run this project as
    flutter run --no-sound-null-safety
    or, upgrade pspec.yaml file, as suggested
    change line #9 to sdk: >=2.12.0 < 3.0.5
